export const Route = {
  Home: '/',
  History: '/history/',
  Foundation: '/foundation/',
  Donate: '/foundation/donate/',
  About: '/about/',
  Brands: '/brands/',
  Terms: '/terms-and-conditions/',
  Categories: '/collection/categories/',
  Barometer: '/collection/items/',
  NewArrivals: '/collection/new-arrivals/',
  Admin: '/admin/',
  AddBarometer: '/admin/add-barometer/',
  AddBrand: '/admin/add-brand/',
  AddDocument: '/admin/add-document/',
  AddProduct: '/admin/add-product/',
  EditProduct: '/admin/edit-product/',
  Reports: '/admin/reports/',
  Shop: '/shop/',
  Cart: '/shop/cart',
  CookiePolicy: '/cookies/',
  PrivacyPolicy: '/privacy/',
  Documents: '/documents/',
  Signin: '/signin/',
} as const

export type Route = (typeof Route)[keyof typeof Route]
