[phases.setup]
nixPkgs = ['openssl']
cmds = [
  'apt-get update && apt-get install -y --no-install-recommends libssl3 ca-certificates curl unzip',
  'export BUN_INSTALL=/usr/local && curl -fsSL https://bun.sh/install | bash',
  'printf "export PATH=/usr/local/bin:\\$PATH\n" > /etc/profile.d/bun.sh',
  'bun --version'
]

[phases.install]
cmds = [
  'bun install'
]

[phases.build]
cmds = [
  'bun run build'
]

[variables]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu"
PRISMA_CLI_BINARY_TARGETS = "debian-openssl-3.0.x"

[start]
cmd = 'bun start'
