export const appShortName = 'Barometers realm'
export const appFullName = 'Barometers realm: Antique barometers collection'
export const email = 'leo@shirokov.nl'
export const instagram = 'https://www.instagram.com/jared_and_milo/'
// API Routes
export const googleStorageImagesFolder = 'https://storage.googleapis.com/barometers/'
export const barometersApiRoute = '/api/barometers/'
export const barometerTypesApiRoute = '/api/barometers/types/'
export const manufacturersApiRoute = '/api/barometers/manufacturers/'
export const conditionsApiRoute = '/api/barometers/conditions'
export const imageUploadRoute = '/api/barometers/upload/images/'
