export const appShortName = 'Barometers realm'
export const appFullName = 'Barometers realm: Antique barometers collection'
export const email = 'leo@shirokov.nl'
export const instagram = 'https://www.instagram.com/jared_and_milo/'
export const twitterAccount = '@barometer_realm'
// API Routes
export const googleStorageImagesFolder = 'https://storage.googleapis.com/barometers/'
export const barometersApiRoute = '/api/barometers/'
export const barometerTypesApiRoute = '/api/barometers/types/'
export const manufacturersApiRoute = '/api/barometers/manufacturers/'
export const conditionsApiRoute = '/api/barometers/conditions'
export const imageUploadApiRoute = '/api/barometers/upload/images/'
// Frontend routes
export const barometerTypesRoute = '/collection/types/'
export const barometerRoute = '/collection/items/'
