export { PropertyCard } from './property-card'
export { default as conditionsImg } from './images/conditions.png'
export { default as datingImg } from './images/dating.png'
export { default as dimensionsImg } from './images/dimensions.png'
export { default as manufacturerImg } from './images/manufacturer.png'
export { default as serialNoImg } from './images/serialno.png'
export { default as subcategories } from './images/subcategories.png'
