name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west4
  REPO_NAME: barometers

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Debug variables
        run: |
          echo "PROJECT_ID: $PROJECT_ID"
          echo "REPO_NAME: $REPO_NAME"
          echo "GITHUB_SHA: $GITHUB_SHA"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag the docker image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO_NAME: barometers
        run: docker buildx build --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA . --build-arg AUTH_SECRET=${{ secrets.AUTH_SECRET }} --build-arg GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }} --build-arg GCP_CLIENT_EMAIL=${{ secrets.GCP_CLIENT_EMAIL }} --build-arg GCP_PRIVATE_KEY=${{ secrets.GCP_PRIVATE_KEY }} --build-arg GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} --build-arg NODE_ENV=${{ secrets.NODE_ENV }}
      
        

      - name: Push the image to the Google Container Registry (GCR)
        run: docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Deploy
        run: |
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --platform "managed" \
          --quiet
