name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west4
  REPO_NAME: barometers

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag the docker image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO_NAME: barometers
        run: |
          echo "${{ secrets.AUTH_SECRET }}" > /tmp/auth_secret
          echo "${{ secrets.GCP_CLIENT_EMAIL }}" > /tmp/gcp_client_email
          echo "${{ secrets.GCP_PRIVATE_KEY }}" > /tmp/gcp_private_key
          echo "${{ secrets.MONGODB_URI }}" > /tmp/mongodb_uri
          echo "${{ secrets.NEXTAUTH_SECRET }}" > /tmp/nextauth_secret

          DOCKER_BUILDKIT=1 docker buildx build \
            --tag "gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA" . \
            --secret id=AUTH_SECRET,src=/tmp/auth_secret \
            --secret id=GCP_CLIENT_EMAIL,src=/tmp/gcp_client_email \
            --secret id=GCP_PRIVATE_KEY,src=/tmp/gcp_private_key \
            --secret id=MONGODB_URI,src=/tmp/mongodb_uri \
            --secret id=NEXTAUTH_SECRET,src=/tmp/nextauth_secret \
            --build-arg "GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }}" \
            --build-arg "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --build-arg "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" \
            --build-arg "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" \
            --build-arg "NODE_ENV=${{ secrets.NODE_ENV }}" \
            --push

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --platform "managed" \
          --quiet

      - name: Update Cloud Run environment variables with actual URL
        run: |
          SERVICE_URL=$(gcloud run services describe $REPO_NAME \
            --platform managed \
            --region $REGION \
            --format 'value(status.url)')
          gcloud run services update $REPO_NAME \
            --region $REGION \
            --update-env-vars NEXTAUTH_URL="$SERVICE_URL",NEXT_PUBLIC_BASE_URL="$SERVICE_URL"
